services:
  bot:
    build: .
    env_file:
      - .env
    environment:
      - WEBAPP_URL=http://bot:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - migrate
    networks:
      - bot-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bot-network

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    networks:
      - bot-network

  migrate:
    build: .
    command: sh /app/scripts/migrate.sh
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: 